// Chunk G re-baseline. Every seeded number in this project predates the v2.4 adoption and
// is re-measured here; balance-results-v3/v4 were removed as pre-adoption evidence.
// This harness MEASURES. It never tunes: no canonical numeric is written from a result.
const fs=require('node:fs');for(const f of ['data/catalog','data/relics','systems/rng','systems/adventurer','systems/dungeon','systems/meta','systems/save','systems/shop','systems/relics','systems/run','ui/presentation','systems/simulation'])require('../dist/'+f+'.js');
const seeds=Number(process.argv[2])||300,out={version:5,canonicalSet:'GUILD24_CANONICAL_v2.4.0',seedsPerStrategy:seeds,seedPrefix:'revision-',note:'Deterministic strategy heuristics; not human first-clear rates. Counterfactual comparison reuses initial RNG state; branch consumption may diverge.',cohorts:[]};
// The engaged strategies carry the run comparison; the four minimal-engagement strategies
// are the direct subject of RUN-Q30 / ECO-Q12 / DUN-Q20.
const strategies=[['beginner','adaptive','hybrid'],['greedy','overcharge','premium'],['protective','half','vip'],['balanced','full','hybrid'],['skilled','adaptive','expedition'],['random','adaptive','hybrid'],['neglect','adaptive','hybrid'],['balanced','vip','vip'],...['rotation','vip','premium','expedition','fresh','customer','hybrid','none'].map(build=>['balanced','adaptive',build]),['zero-sale','adaptive','hybrid'],['zero-order','adaptive','hybrid'],['zero-supply','adaptive','hybrid'],['poverty','adaptive','hybrid']];
for(const [policy,pricing,build]of strategies){const r=Debug.simulate(seeds,policy,null,pricing,build);out.cohorts.push(r);console.log(JSON.stringify({policy,pricing,build,day:Number(r.averageDay.toFixed(1)),reach:r.reachRate,bossGivenReach:r.bossWinGivenReach,clear:r.overallClearRate,deaths:r.averageDeaths,gold:Math.round(r.averageMoney),metaXP:Math.round(r.metaXPPerRun),knowledge:Number(r.knowledgePerRun.toFixed(1)),relicSpend:Math.round(r.relicSpend/seeds),impact:Number((r.impact.improved/r.impact.samples).toFixed(3))}));fs.writeFileSync('tests/balance-results-v5.json',JSON.stringify(out,null,2));}
