const fs=require('node:fs');for(const f of ['data/catalog','data/relics','data/copy','systems/rng','systems/adventurer','systems/dungeon','systems/meta','systems/save','systems/shop','systems/relics','systems/run','ui/presentation'])require('../dist/'+f+'.js');fs.mkdirSync('reports',{recursive:true});
const header=(cols)=>'| '+cols.join(' | ')+' |\n| '+cols.map(()=>'---').join(' | ')+' |\n';
let price='# 상품 가격 · 현재 데이터 기준\n\n정수 Gold, Math.round 반올림. 원가 할인은 실제 발주 조합에 따라 별도 적용. 부담은 DAY1 기본 소지금 범위 88~199G에 대한 참고값이며 실제 방문객 분포는 밸런스 보고서를 따른다.\n\n'+header(['상품','매입','50%','100%','150%','이익 50','이익 100','이익 150','역할','등장 조건','DAY1 정가 부담']);
for(const it of DATA.items){const half=Math.round(it.sell*.5),over=Math.round(it.sell*1.5);price+='| '+[it.name,it.buy,half,it.sell,over,half-it.buy,it.sell-it.buy,over-it.buy,Presentation.rows(it.effects).map(r=>r.label+' '+r.text).join(' · '),it.unlock?DATA.unlocks[it.unlock][0]+' 해금 후':'DAY1부터 후보',Math.round(it.sell/199*100)+'~'+Math.round(it.sell/88*100)+'%'].join(' | ')+' |\n';}fs.writeFileSync('reports/ITEM-PRICES.md',price);
const affinity={warrior:['bar','kit','cloak'],archer:['rope','energy','battery'],mage:['mana','candy','kit'],priest:['kit','candy','rice'],rogue:['rope','stone','energy'],berserker:['bar','kit','wine']};
const advantage={warrior:['fire','snow'],archer:['spider','slime'],mage:['crypt','fire'],priest:['crypt','snow'],rogue:['spider','slime'],berserker:['fire','snow']};
let matrix='# 직업 · 상품 · 던전 대응 매트릭스\n\n6직업 모두 생성·성장·승급·도감·메타 해금·보급·보스 경로를 유지한다. 아래 궁합은 실제 효과와 능력에 따른 운영 후보이며, 독립적인 전용 배율 보너스를 의미하지 않는다. 유리한 던전은 설계상 경향으로, 무보급 성공 보장이 아니다.\n\n'+header(['직업','주요 능력','압박 능력','궁합 상품','범용 상품','던전 장점 경향','대응 선택','특성·점포지원 접점','상태']);
for(const j of DATA.jobs){const ranked=Adventurer.keys.map((k,i)=>({k,v:j.stats[i]+9*j.growth[i]})).sort((a,b)=>b.v-a.v);matrix+='| '+[j.name,ranked.slice(0,2).map(x=>Presentation.labels[x.k]).join('·'),ranked.slice(-2).map(x=>Presentation.labels[x.k]).join('·'),affinity[j.id].map(id=>DATA.itemBy[id].name).join('·'),'생수·상급 포션·귀환석',advantage[j.id].map(id=>DATA.dungeonBy[id].name).join('·'),'기동/저항/부상 방어로 약점 보완',j.id==='warrior'||j.id==='berserker'?'대식가·신선식품·원정 전문':j.id==='mage'||j.id==='priest'?'포션체질·단골 육성·원정 전문':'카페인중독·원정 전문·고마진',j.unlock?'메타 해금 후 플레이 가능':'기본 플레이 가능'].join(' | ')+' |\n';}
matrix+='\n## Family 대응 경로\n\n'+header(['Family','Tier I','Tier II','Tier III','직접 대응','보조 대응','기본 능력','보험']);
const routes={spider:['mask','rope','강인함·기동'],slime:['cloak','boots','기동·강인함'],fire:['ice','highpotion','전투·강인함'],crypt:['wine','battery','정신·전투'],snow:['heat','compass','강인함·음식·정신']};for(const [id,tiers]of Object.entries(DATA.familyTiers)){const r=routes[id];matrix+='| '+[DATA.dungeonBy[id].name,...tiers.map(h=>h.map(k=>DATA.hazards[k]).join('·')),DATA.itemBy[r[0]].name,DATA.itemBy[r[1]].name,r[2],'귀환석·구급키트'].join(' | ')+' |\n';}fs.writeFileSync('reports/COVERAGE.md',matrix);
let traits='# 특성 20종 점검\n\n공개 문구는 계산 데이터로 생성한다. 허세는 최신 추가 사양에 따라 경험치 효과를 제거하고 바가지 수용 효과로 교체했다.\n\n'+header(['특성','현재 실제 효과','적용 경로','방향']);
for(const t of DATA.traits)traits+='| '+[t.name,Presentation.traitText(t.id),['frugal','impulse','showoff'].includes(t.id)?'구매 의사 / 허세 목적지 표시':'원정 준비 → 전투·환경·탈출·성장',DATA.traitDirections[t.direction]].join(' | ')+' |\n';traits+='\n동시 생성·승급 금지: '+DATA.traitExclusions.map(pair=>pair.map(id=>DATA.traitBy[id].name).join(' ↔ ')).join(', ')+'.\n\n음식 배율은 포만감·보급·강인함에만 적용한다. 포션 배율은 포션의 강인함에만 적용한다. 저항과 부작용은 카테고리 배율에서 제외한다. 특성 ID와 특정 점포지원 쌍만을 위한 별도 전용 보너스는 없다.\n';fs.writeFileSync('reports/TRAITS.md',traits);
console.log('Wrote source-derived prices, coverage and trait audit.');
