const fs=require('node:fs');require('../dist/data/catalog.js');require('../dist/data/relics.js');const data=JSON.parse(fs.readFileSync('tests/balance-results-v3.json','utf8')),pct=x=>(x*100).toFixed(1)+'%',num=x=>Number(x).toFixed(1),table=h=>'| '+h.join(' | ')+' |\n| '+h.map(()=>'---').join(' | ')+' |\n',row=v=>'| '+v.join(' | ')+' |\n';
let md='# PASS 3 — 최종 구현본 재측정\n\n각 전략 300 Seed, 16개 전략 조합, 총 4,800 Run. 모든 조합은 revision-0~299를 사용한다. 무작위 결과의 표본 오차가 있으며 같은 Seed도 행동에 따라 RNG 소비 경로가 갈라진다. 이 결과는 자동 정책 비교이며 사람의 첫 클리어율이 아니다.\n\nDAY30 도달률의 분모는 전체 Run, 도달 후 보스 승률의 분모는 DAY30 도달 Run, 전체 클리어율의 분모는 전체 Run이다. 300회에서 관측값이 50%이면 단순 이항 95% 오차폭은 약 ±5.7%p다. 작은 순위 차이에 의미를 부여하지 않는다.\n\n'+table(['정책 / 가격 / 유물 방향','도달 수 / Run','DAY30','보스 승리 / 도달','도달 후 승률','전체 클리어','평균 사망','평균 최종 Gold','평균 유물 지출']);
for(const c of data.cohorts)md+=row([c.policy+' / '+c.pricing+' / '+c.build,c.reached30+'/'+c.runs,pct(c.reachRate),c.wins+'/'+c.reached30,c.reached30?pct(c.bossWinGivenReach):'분모 0',pct(c.overallClearRate),num(c.averageDeaths),num(c.averageMoney),num(c.relicSpend/c.runs)]);
md+='\n## 해석과 한계\n\n- 모든 거래를 반값으로 처리하는 정책은 운영비·발주비를 회수하지 못했다. 반값을 금지할 근거가 아니라 선택 투자가 필요한 이유다.\n- 선택 VIP 투자는 자동 정책 중 높은 성과를 보였다. 약한 NPC 방치 정책도 상당한 클리어율을 내므로 장기 고객가치 설계가 충분히 검증되었다고 선언하지 않는다.\n- 일반 정책의 DAY30 도달률은 참고 목표 50~65%보다 높다. 보스만 강화하지 않았다. 운영비·현금축적·고객 성장의 상대 속도가 다음 실험 대상이다.\n- Skilled는 현재 휴리스틱의 이름이다. 전문가 사람 플레이를 대체하지 않는다. 보스 팀은 레벨 우선 3명, 마지막 발주는 단순 정책이라 최적 팀 구성·아이템 조합을 과소평가할 수 있다.\n- none은 DAY0 무료 1개만 선택하고 이후 유료 유물을 사지 않는다.\n- 기본 계정 측정이므로 메타 해금 직업·상품의 전수 성능 평가가 아니다. 6직업의 구현 경로와 설계상 대응은 COVERAGE.md에 별도로 기록했다.\n- 유물 보유별 성과는 조건부 상관관계다. 독립적인 인과 ROI, 가격 회수 기간, 픽 자체의 최적성을 뜻하지 않는다.\n\n## DAY 스냅샷 — balanced / adaptive / hybrid\n\nGold·재고는 발주 전, Peak는 발주 직후 표본의 평균이다. 방문객 지갑과 레벨은 그날 방문객 기준. DAY30은 최종팀 기준이라 동일 모수 비교가 아니다.\n\n'+table(['DAY','Run 수','Gold','재고','발주 후 재고','방문/팀 수','평균 Lv','지갑 중앙값','지갑 P10/P90','매출','발주비','운영비','150% 감당 비율']);
const c=data.cohorts.find(c=>c.policy==='balanced'&&c.pricing==='adaptive'&&c.build==='hybrid');for(const d of [1,5,10,15,20,25,30]){const x=c.days[d],w=c.wallets[d];md+=row([d,x.samples,num(x.cash/x.samples),num(x.inventory/x.samples),d===30?'—':num(x.peak/x.samples),num(x.visitors/x.samples),num(x.level/x.visitors),w?.median??'—',w?w.p10+'/'+w.p90:'—',d===30?'—':num(x.revenue/x.samples),d===30?'—':num(x.spent/x.samples),d===30?'—':num(x.operating/x.samples),x.offers?pct(x.overAffordable/x.offers):'—']);}
md+='\n150% 감당 비율 분모는 해당 날짜의 방문객×발주 후보 쌍이다. 실제 재고 판매 상황의 전환율과 구분한다. DAY30 경제 일계 누적은 별도 계측 미완료이므로 대시로 표시했다.\n\n## 가격별 실제 시도\n\n'+table(['전략','가격','구매/시도','전환율','매출','기록 원가 차감 이익','단골도 순변화']);for(const cohort of data.cohorts.slice(0,8))for(const [mode,m]of Object.entries(cohort.modes))md+=row([cohort.policy+'/'+cohort.pricing,mode,m.accepted+'/'+m.attempts,pct(m.accepted/m.attempts),m.revenue,m.profit,m.loyalty]);
md+='\n## 원정 준비의 진단값\n\n아이템을 모두 제거한 원정과 준비한 원정을 같은 초기 RNG 상태로 비교했다. 조건 분기가 난수 소비를 달리할 수 있어 엄밀한 전후 인과 실험은 아니다. 플레이어에게 확률로 표시하지 않는다.\n\n'+table(['정책','비교 원정 수','결과 등급 개선 비율','사망→생환 비교 수','평균 본체 능력 합성값','평균 준비 후 합성값']);for(const c of data.cohorts.slice(0,8)){const x=c.impact;md+=row([c.policy+'/'+c.pricing,x.samples,pct(x.improved/x.samples),x.saved,num(x.characterAbility/x.samples),num(x.preparedAbility/x.samples)]);}
md+='\n## 유물 제안·구매 — balanced/adaptive/hybrid\n\n후보 노출은 한 Window당 한 번 집계한다. 무료 DAY0도 구매 횟수에 포함한다. 가격 ROI는 구매 후 생존 편향이 있어 이 표만으로 확정하지 않는다.\n\n'+table(['유물','노출','획득','노출 대비 획득','평균 획득 DAY','평균 가격','보유 Run 클리어']);for(const r of DATA.relics){const p=c.relicPurchases[r.id],o=c.relicOutcomes[r.id];md+=row([r.name,c.relicOffers[r.id]||0,p?.count||0,p?pct(p.count/c.relicOffers[r.id]):'—',p?num(p.day/p.count):'—',p?num(p.spend/p.count):'—',o?pct(o.wins/o.runs):'—']);}
md+='\n## Build 완성 분포 — balanced/adaptive/hybrid\n\nHybrid 유물은 양쪽 태그에 각각 포함한다. 한 Run이 여러 Build 행에 동시에 들어간다.\n\n'+table(['방향','0','1','2','3','4','5+']);for(const [tag,bins]of Object.entries(c.buildCounts))md+=row([DATA.buildNames[tag],...[0,1,2,3,4,5].map(n=>bins[n]||0)]);
md+='\n## 던전별 결과 — balanced/adaptive/hybrid\n\n'+table(['Family:Tier','원정','성공/대성공','퇴각','부상','중상','사망']);for(const [key,x]of Object.entries(c.dungeons))md+=row([key,x.expeditions,x.success,x.retreat,x.injury,x.severe,x.death]);
md+='\n## 아직 필요한 검증\n\n사람 DAY1~30 반복 플레이, 실제 휴대전화 터치·음량, 전체 메타 해금 상태 비교, 유물별 동일 조건 인과 ROI, NPC 투자별 재방문 지연 시간, Lv9→10 독립 비교, DAY20 에이스 사망 후 회복, 특정 전설 없이 클리어 가능성, Counter별 Pity와 실제 수요 다양성. 이를 완료된 것으로 표시하지 않는다. 원시 집계는 tests/balance-results-v3.json에 있다.\n';fs.writeFileSync('reports/BALANCE.md',md);
let relic='# 점포지원 30종\n\nDAY0 무료 3택. DAY5·10·15·20·25·30 유료 3택, 한 Window에 최대 1개. DAY5 후보는 DAY9까지 보류 가능. 가격과 후보는 저장되며 같은 Window 내에서 다시 뽑히지 않는다. 신규 구매는 발주·최종 준비에서만 허용한다. 방문객·운영비 변화는 다음 날부터 적용한다. 이미 생성된 발주 후보는 유물을 산다고 자동 재생성되지 않는다.\n\n'+table(['이름','종류','운영 방향','기준가','기능','DAY30 후보']);for(const r of DATA.relics)relic+=row([r.name,r.kind,r.tags.map(t=>DATA.buildNames[t]).join('·')||'범용',r.price,r.description,r.finalUseful?'가능':'제외']);fs.writeFileSync('reports/RELICS.md',relic);
console.log('Wrote BALANCE.md and RELICS.md');
if(fs.existsSync('reports/operating-experiment.json')){const e=JSON.parse(fs.readFileSync('reports/operating-experiment.json','utf8'));let text='\n## 한 변수 실험 — 운영비 60 → 65G\n\n각 조합 동일 300 Seed. 배포값은 60G로 유지했다.\n\n'+table(['가격/방향','기본 도달률','65G 도달률','기본 클리어','65G 클리어','기본 최종 Gold','65G 최종 Gold']);for(const x of e.cohorts){const b=data.cohorts.find(c=>c.policy==='balanced'&&c.pricing===x.pricing&&c.build===x.build);text+=row([x.pricing+'/'+x.build,pct(b.reachRate),pct(x.reach),pct(b.overallClearRate),pct(x.clear),num(b.averageMoney),num(x.gold)]);}text+='\n결론: 단순 소폭 운영비 인상은 일반 전략의 높은 도달률을 충분히 바꾸지 못했다. 사람 플레이 없이 비용을 계속 올려 목표값에 맞추지 않았다. 이 후보는 미채택. 다음에는 고객 성장과 발주·보험의 실제 가치가 도달 곡선에 미치는 영향을 분리해 검증해야 한다.\n';fs.appendFileSync('reports/BALANCE.md',text);}
